services:
  pos-app:
    build: .
    container_name: pos_apotek_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://pos-apotek.sofyan.app
      - DB_CONNECTION=mysql
      - DB_HOST=pos-db
      - DB_PORT=3306
      - DB_DATABASE=apotek_db
      - DB_USERNAME=apotek_user
      - DB_PASSWORD=apotek_pass
    depends_on:
      - pos-db

  pos-db:
    image: mysql:8.0
    container_name: pos_apotek_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: apotek_db
      MYSQL_USER: apotek_user
      MYSQL_PASSWORD: apotek_pass
      MYSQL_ROOT_PASSWORD: root_secret_password
    volumes:
      - pos-db-data:/var/lib/mysql

volumes:
  pos-db-data: